name: Swift Tests

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  tests:
    name: tests
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@0.0.1
    with:
      linux_exclude_swift_versions: '[{"swift_version":"5.9"},{"swift_version":"5.10"}]'
      windows_exclude_swift_versions: '[{"swift_version":"5.9"},{"swift_version":"5.10"}]'
